updating configure to acknowledge adamant lib and adding object size parameter to hpcrun.in

diff --git a/src/tool/hpcrun/scripts/hpcrun.in b/src/tool/hpcrun/scripts/hpcrun.in
--- a/src/tool/hpcrun/scripts/hpcrun.in
+++ b/src/tool/hpcrun/scripts/hpcrun.in
@@ -286,6 +286,22 @@ do
             shift
             ;;
 
+	# --------------------------------------------------
+
+        --enable-object-level )
+	    echo "HPCRUN_OBJECT_LEVEL is activated"
+            export HPCRUN_OBJECT_LEVEL=1
+            ;;
+
+	# --------------------------------------------------
+
+	--object-size-threshold )
+            arg_ok "$1" || die "missing argument for $arg"
+	    export OBJECT_SIZE_THRESHOLD=$1
+	    export HPCRUN_OBJECT_LEVEL=1
+            shift
+            ;;
+
 	--bulletin-board-size )
             arg_ok "$1" || die "missing argument for $arg"
 	    BULLETIN_BOARD_SIZE=$1
@@ -360,6 +376,7 @@ do
 done
 
 export BULLETIN_BOARD_SIZE
+export OBJECT_SIZE_THRESHOLD
 export WATCHPOINT_SIZE
 
 # Add default sampling source if needed.
